# Generated by Django 3.1.13 on 2021-12-04 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Асессоры',
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Название критерия')),
                ('options', models.TextField(blank=True, null=True, verbose_name='Возможные ответы и баллы за них')),
                ('max_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='Максимальное кол-во баллов за критерий')),
            ],
            options={
                'verbose_name_plural': 'Критерии',
            },
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, verbose_name='Название номинации')),
                ('criterions', models.ManyToManyField(to='api.Criterion', verbose_name='Критерии')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники номинации')),
            ],
            options={
                'verbose_name_plural': 'Номинации',
            },
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Жюри',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, verbose_name='Название мероприятия')),
                ('asessors', models.ManyToManyField(to='api.Asessor', verbose_name='Асессоры')),
                ('jury', models.ManyToManyField(to='api.Jury', verbose_name='Жюри')),
                ('nominations', models.ManyToManyField(to='api.Nomination', verbose_name='Номинации')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
