# Generated by Django 3.1.13 on 2021-12-04 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211205_0348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scores',
            options={'verbose_name_plural': 'Оценки'},
        ),
    ]
