# Generated by Django 3.1.13 on 2021-12-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211205_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='jury_priority',
            field=models.CharField(choices=[('top', 'ВЫСОКИЙ'), ('okay', 'ВСЕ ВЕРНО'), ('bad', 'НИЗКИЙ')], default='JANUARY', max_length=128),
        ),
    ]
