# Generated by Django 3.1.13 on 2021-12-05 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211205_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='nomination',
        ),
        migrations.AddField(
            model_name='scores',
            name='criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.criterion', verbose_name='Критерий'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='jury_priority',
            field=models.CharField(choices=[('top', 'ВЫСОКИЙ'), ('okay', 'ВСЕ ВЕРНО'), ('bad', 'НИЗКИЙ')], default='okay', max_length=128),
        ),
    ]
